"""lead name -> not unique

Revision ID: dd26e2b67457
Revises: 143e1a4ffa37
Create Date: 2025-05-08 11:00:06.110308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd26e2b67457'
down_revision: Union[str, None] = '143e1a4ffa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contact_us_form_leads_name_key', 'contact_us_form_leads', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contact_us_form_leads_name_key', 'contact_us_form_leads', ['name'])
    # ### end Alembic commands ###
